# Generated by Django 4.0.4 on 2022-09-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default='ww', max_length=1000),
            preserve_default=False,
        ),
    ]
