# Generated by Django 4.0.4 on 2022-09-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_follow_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='number_of_followers',
            field=models.IntegerField(default=0),
        ),
    ]
