# Generated by Django 4.0.4 on 2022-09-29 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_follow_followers_alter_follow_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatever', to=settings.AUTH_USER_MODEL),
        ),
    ]
