# Generated by Django 4.0.4 on 2022-09-30 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_follow_following_alter_follow_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='number_of_following',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
